

#
# This file is autogenerated during plugin_quickstart and overwritten during
# plugin_makedist. DO NOT CHANGE IT if you plan to use plugin_makedist to update 
# the distribution.
#

from setuptools import setup, find_packages

kwargs = {'author': 'Kenneth T. Moore',
 'author_email': 'kenneth.t.moore-1@nasa.gov',
 'classifiers': ['Intended Audience :: Science/Research',
                 'Topic :: Scientific/Engineering'],
 'description': 'OpenMDAO component wrapper for the Overflow (OVERset grid FLOW solver)',
 'download_url': '',
 'entry_points': '[openmdao.component]\noverflow_wrapper.overflow_wrapper.OverflowWrapper=overflow_wrapper.overflow_wrapper:OverflowWrapper',
 'include_package_data': True,
 'install_requires': ['openmdao.main'],
 'keywords': ['openmdao'],
 'license': 'Apache License, Version 2.0',
 'maintainer': 'Kenneth T. Moore',
 'maintainer_email': 'kenneth.t.moore-1@nasa.gov',
 'name': 'overflow_wrapper',
 'package_data': {'overflow_wrapper': ['sphinx_build/html/usage.html',
                                       'sphinx_build/html/py-modindex.html',
                                       'sphinx_build/html/genindex.html',
                                       'sphinx_build/html/search.html',
                                       'sphinx_build/html/srcdocs.html',
                                       'sphinx_build/html/index.html',
                                       'sphinx_build/html/objects.inv',
                                       'sphinx_build/html/searchindex.js',
                                       'sphinx_build/html/.buildinfo',
                                       'sphinx_build/html/pkgdocs.html',
                                       'sphinx_build/html/_sources/pkgdocs.txt',
                                       'sphinx_build/html/_sources/srcdocs.txt',
                                       'sphinx_build/html/_sources/index.txt',
                                       'sphinx_build/html/_sources/usage.txt',
                                       'sphinx_build/html/_modules/index.html',
                                       'sphinx_build/html/_modules/overflow_wrapper/overflow_wrapper.html',
                                       'sphinx_build/html/_static/underscore.js',
                                       'sphinx_build/html/_static/pygments.css',
                                       'sphinx_build/html/_static/basic.css',
                                       'sphinx_build/html/_static/file.png',
                                       'sphinx_build/html/_static/sidebar.js',
                                       'sphinx_build/html/_static/jquery.js',
                                       'sphinx_build/html/_static/default.css',
                                       'sphinx_build/html/_static/minus.png',
                                       'sphinx_build/html/_static/doctools.js',
                                       'sphinx_build/html/_static/searchtools.js',
                                       'sphinx_build/html/_static/plus.png',
                                       'test/overflow1_out.inp',
                                       'test/openmdao_log.txt',
                                       'test/overflow1.inp',
                                       'test/test_overflow_wrapper.py']},
 'package_dir': {'': 'src'},
 'packages': ['overflow_wrapper'],
 'url': 'https://github.com/OpenMDAO-Plugins/overflow_wrapper',
 'version': '0.4',
 'zip_safe': False}


setup(**kwargs)

